module.exports = [
    '¿Cual es la frase que pronunció Iñigo Montoya antes de matar al asesino de su padre?',
    '¿Quien interpretaba a la medium de Ghost?',
    '¿Qué vendía el contacto ciego de Top Secret?',
    '¿Con quién estaba condenada a casarse la Princesa Vespa?',
    '¿Como se llamaba el malo de La loca historia de las galaxias?',
    '¿Qué velocidad debe alcanzar el Delorean de “Regreso al Futuro” para viajar en el tiempo?',
    '¿Quien fué el primero robot en conseguir la nacionalidad norteamericana?',
    '¿Que usaban en Demolition Man para limpiarse el "pompis"?',
    '¿Quien interpretó a Conan de pequeño?',
    '¿Cómo se llama la esposa de Pijus Magnificus?',
    '¿Cómo se llama el padre de Chewaka?',
    '¿A que animal tenía miedo Indiana Jones?',
    '¿Cómo se designa al pequeño y ligero caza utilizado por el Imperio Galáctico?',
    '¿De que planeta es originario Darth Vader?',
    '¿Cuál es el nombre de pila del padre de Luke Skywalker?',
    '¿Qué actriz de Friends aparecía en Masters del Universo?',
    '¿Como se llama el personaje de Kurt Russell en 1997: Escape en Nueva york?',
    '¿Actor interpretaba de El Príncipe de Zamunda?',
    '¿Como se llama la mujer de la que se enamora Doc en Regreso al futuro III?',
    '¿Cuantas películas se han hecho de Expediente X?',
    '¿De que universidad vasca era catedrático de teología el padre Berriartua?',
    'En Mallrats, ¿que dibujo se supone que aparece en el cuadro magico del centro comercial si lo miras durante unos segundos?',
    '¿Cual es el color de Quentin Tarantino en Reservoir Dogs?',
    '¿Cual es el autentico nombre de El Vengador toxico?',
    '¿Cómo se puede saber si alguien es una bruja?',
    '¿Cual es el personaje de Bruce Willis en La jungla de cristal?',
    '¿Cómo se llama el compañero de John McLane en "La jungla de Cristal III:La venganza"?',
    '¿Como se llamaba el fantasma verde de Los Cazafantasmas?'
    '¿A qué estaban enganchados los extraterrestres de "Distrito 9"?',
'¿Cómo se llama el barco de Russell Crowe en "Master and Commander"?',
'¿Cómo se llama el malo de "El Mariachi" que siempre vestía de blanco?',
'¿Cómo se llama la banda rival de Los Pájaros de "Grease"?',
'¿Cómo se llama la república que gobierna el protagonista de "El Dictador"?',
'¿Cómo se llamaba el cuchillo mágico de "El Chico de Oro"?',
'¿Cómo se llamaba el hotel de "La Jungla de Cristal"?',
'¿Cómo se llamaba el jefe de los Gremlins malos?',
'¿Cómo se llamaba el palacio de Charles Foster Kane?',
'¿Cómo se llamaba el ser creado por Lex Luthor en Superman IV?',
'¿Cómo se llamaba la bella durmiente?',
'¿Cómo se llamaba la compañera de Robocop?',
'¿Cómo se llamaba la esposa de Pijus Magníficus?',
'¿Cómo se llamaba la máquina de feria que le concedió el deseo a Tom Hanks en "Big"?',
'¿Cómo se llamaba la serie de la que Mia Wallace sólo coprotagonizó un capítulo?',
'¿Cuál de estas actrices noa parecía en los posters de "Cadena Perpetua"?',
'¿Cuál de estas películas no ganó once Óscars?',
'¿Cuál de los siguientes superhéroes no aparece en la película de los Vengadores?',
'¿Cuál era el rango militar de Al Pacino en "Esencia de Mujer"?',
'¿Cuál era la nacionalidad de Tony Montana?',
'¿Cuál era nombre en clave de Quentin Tarantino en "Reservoir Dogs"?',
'¿Cuál es el cóctel favorido de Jeffrey Lebowski?',
'¿Cuál es el nombre de pila de Bourne?',
'¿Cuál es el título original de "Los Bicivoladores"?',
'¿Cuál es la primera regla para sobrevivir en Zombieland?',
'¿Cuál es la última parte publicada de la saga "Crepúsculo"? ',
'¿Cuáles fueron las últimas palabras de Kevin Spacey en "L.A. Confidential"? ',
'¿Cuántos dedos tenía Íñigo Montoya?',
'¿Cuántos dedos tiene Yoda en cada mano?',
'¿Cuántos haces emite la mira láser de Predator?',
'¿De qué color es el planeta Yavin visto desde el espacio?',
'¿De qué se disfrazó Daniel Larusso en la fiesta del instituto en "Karate Kid"? ',
'¿En cuántos puntos supera el Halcón Milenario la velocidad de la luz?',
'¿En qué ciudad se desarrolla "El Vengador Tóxico"?',
'¿En qué conflicto fue héroe de guerra el presidente de E.E.U.U. en "Independence Day"?',
'¿En qué país el Pirata Roberts desarrolló su inmunidad a la Jokaína?',
'¿En qué planeta murió Jango Fett?',
'¿En qué planeta tiene su sede la casa Harkonnen?',
'¿Por qué quería Jeffrey Lebowski que le indemnizaran?',
'¿Quál es la verdadera identidad de Ironman?',
'¿Qué actor dobla al camello que vende supositorios de opio en "Trainspotting"?',
'¿Qué actor era la envidia en "Seven"?',
'¿Qué actor español interpretó de niño a Conan el Bárbaro?',
'¿Qué actor interpreta el papel de Chris Chambers en "Cuenta Conmigo"?',
'¿Qué actor pone voz a Darth Vader en versión original?',
'¿Qué actor protagonizó "Los Inmortales"?',
'¿Qué actor protagonizó junto a Kyle Gass la película "Tenacious D"?',
'¿Qué actor se interpreta a sí mismo en Zombieland?',
'¿Qué bebida toma Cafe Au Lait en "Top Secret"?',
'¿Qué canción baila Ted Striker en "Aterriza como Puedas"?',
'¿Qué canción interpreta Marty McFly en "Regreso al Futuro"?',
'¿Qué cantidad de energía eléctrica necesitaba el coche de "Regreso al Futuro"?',
'¿Qué componente de The Beatles no ha aparecido nunca en "Los Simpsons"?',
'¿Qué hay colgado sobre el salpicadero de el Halcón Milenario?',
'¿Qué monumento manipuló Superman en "Superman 3"?',
'¿Qué nombre en clave tenía el líder de la resistencia de "Top Secret"?',
'¿Qué película parodiaba a "Scream"?',
'¿Qué planta compra Kevin Costner en "Waterworld"?',
'¿Qué presentador español dobló la voz de Stuart Little?',
'¿Qué supuesto pasaje de la Biblia reproduce Samuel L. Jackson en "Pulp Fiction"?',
'¿Qué velocidad, en km/h, necesitaba alcanzar el coche de "Regreso al Futuro"?',
'¿Qué vendía el contacto ciego de "Top Secret"?',
'¿A qué hora se despertaba todos los días Bill Murray en "Atrapado en el Tiempo"?',
'¿Cómo es ejecutada Bjork en "Bailando en la Oscuridad"?',
'¿Cómo se escribe correctamente el apellido de Arnold?',
'¿Cómo se llama el arma multiusos que usa Eddie Murphy en "Superdetective en Hollywood III"?',
'¿Cómo se llama el pene de Ford Farlein?',
'¿Cómo se llama la nave nodriza de "Alien Resurrección"?',
'¿Cómo se llama la protagonista de "El diario de Noa"?',
'¿Cómo se llamaba el barco de Willie el Tuerto?',
'¿Cómo se llamaba el equipo de baloncesto rival de  Michael J. Fox en "Teen Wolf"?',
'¿Cómo se llamaba el gato de la nave "Nostromo"?',
'¿Cómo se llamaba el grupo de technopop de los secuestradores  de "El Gran Lebowski"?',
'¿Cómo se llamaba el instituto de "Grease"?',
'¿Cómo se llamaba el padre de Aragorn?',
'¿Cómo se llamaba el padre de Brian en "La Vida de Brian"?',
'¿Cómo se llamaba la hermana de Tony Montana?',
'¿Con quién se iba a casar la princesa Vespa?',
'¿Contra qué personaje histórico le gustaría pelear a Edward Norton en "El Club de la Lucha"?',
'¿Cuál de estas figuras de acción Star Wars no aparece en "E.T."?',
'¿Cuál de los siguientes personajes nunca ha sido doblado por Constantino Romero?',
'¿Cuál era el nombre de Ripley?',
'¿Cuál era el verdadero nombre de Rizzo en "Grease"?',
'¿Cuál es el grito de guerra de Turboman?',
'¿Cuál es el nombre artístico del protagonista de "Boogie Nights"?',
'¿Cual es el nombre de la espada de Theoden?',
'¿Cuál es la profesión de Bitelchús?',
'¿Cuáles eran los libros favoritos de Johnny 5?',
'¿Cuántos agentes disparan en el final de "Matrix"?',
'¿De qué franquicia es la pizza que se come Gordi al final de "Los Goonies"?',
'¿De qué región era originario Espartaco?',
'¿De qué se disfraza Tolouse Loutrec en el musical "Spectacular Spectacular"? ',
'¿En qué animal se gestó el alien de la versión original de "Alien 3"?',
'¿En qué ciudad transcurre "Blade Runner"?',
'¿En qué cuatro años diferentes transcurre la trilogía de "Regreso al Futuro"?',
'¿En qué Estado de E.E.U.U. transcurre "Cuarta Fase"?',
'¿En qué localidad transcurre "Atrapado en el Tiempo"?',
'¿En qué monumento luchan Bruce Lee y Chuck Norris en "Way of the Dragon"?',
'¿En qué país asiático transcurre "Espías como Nosotros"?',
'¿En qué souvenir se escondía el detonador nuclear de "Frenético"?',
'¿Entre qué cuatro animales puede elegir cada alumno de la Escuela de Hogwarts?',
'¿Por qué se celebra el "Día del Orgullo Friki" el 25 de Mayo?',
'¿Qué actor era la ira en "Seven"?',
'¿Qué actores doblan en castellano a los perros de "Mira Quién Habla También"?',
'¿Qué animal tenía como mascota Álex en "La Naranja Meecánica"?',
'¿Qué banda de rock interpreta a unos surfistas chungos en "Le Llaman Bhodi"?',
'¿Qué canción sonaba todos los días en el radio despertador de "Atrapado en el Tiempo"?',
'¿Qué cantante interpretó a una guerrera en "Conan el Destructor"?',
'¿Qué droga consumen Conan y Subotai en "Conan el Bárbaro"?',
'¿Qué llevan atado a la frente los corredores de la carrera del hombre pájaro de "Rapa Nui"?',
'¿Qué nombre adoptó Dalton dentro del Club de los Poetas Muertos?',
'¿Qué número llevaba Herbie en el capó?',
'¿Qué parte del cuerpo se podía encajar y desencajar Mel Gibson en la saga de "Arma Letal"?',
'¿Qué rango tenía Ripley en "Alien"?',
'¿Quién es el autor de la banda sonora de "El Pelotón Chiflado"?',
'¿Quién protagonizó "El Semental Italiano"?',
'¿A cuánto ascendía la cuenta bancaria fraudulenta de "Ghost"?',
'¿A qué sindicato pertenecía Johnny de "Dirty Dancing"?',
'¿A qué tenor suplantó el Tenente Frank Drevin en "Agárralo como Puedas"?',
'¿Cómo murió Zampo el payaso?',
'¿Cómo se apodaba el camionero colega de Burt Reynolds en "Los Caraduras"?',
'¿Cómo se llama el club del principio de "Indiana Jones y el Templo Maldito"?',
'¿Cómo se llama el entrenador del equipo de baloncesto de Michael J. Fox en "Teen Wolf"?',
'¿Cómo se llama el grupo con el que Marty McFly toca Johnny B. Good?',
'¿Cómo se llama el mineral que trata de extraer la empresa de "Avatar"?',
'¿Cómo se llama el orangután colega de Clint Eastwood en "Duro de Pelar"?',
'¿Cómo se llama el simulador de HAL 9000 en la Tierra?',
'¿Cómo se llama se llama el asiático que proteje al Oráculo en la Matrix?',
'¿Cómo se llamaba el personaje protagonista de "Commando"?',
'¿Cómo se llamaba el robot triturador de "El Abismo Negro"?',
'¿Cómo se llamaba el teatro donde fue presentado King Kong en la versión de Peter Jackson?',
'¿Cómo se llamaba el tío de William Wallace?',
'¿Cómo se llamaba la nave comandante imperial de la batalla de Endor?',
'¿Cómo se llamaban los cuatro caballos que tiraban del carro de Judá Ben-Hur?',
'¿Cómo se llamaban los tres villanos de "Superman II?',
'¿Cómo se llamanba el bate de béisbol que usa Robert Redford en "El Mejor"?',
'¿Cómo se tituló en España la película de Robert Zemeckis "Used Cars"?',
'¿Con qué nombre se bautizó al monolito de "2.001, una Odisea del Espacio"?',
'¿Con qué tipo de lana estaba obsesionado Ed Wood?',
'¿Cuál de estos personajes no aparece en "Los Feos También Mojan"?',
'¿Cuál de los siguientes actores no trabajó en Las Aventuras de Priscila?',
'¿Cuál de los siguientes miembros de la resistance de "Top Secret" no existe?',
'¿Cuál de los siguientes miembros de la resistance de "Top Secret" no existe?',
'¿Cuál era el nombre artístico de la señora Lebowski?',
'¿Cuál era el verdadero nombre de Rita Hayworth?',
'¿Cuál era la habitación maldita de "El Resplandor"?',
'¿Cuál es el signo zodiacal de Douglas Quaid en "Desafío Total"?',
'¿Cuál es la contraseña para entrar en la casa de "Eyes Wide Shut"?',
'¿Cuáles eran las proporciones dimensionales del monolito de "2001 una Odisea del Espacio"?',
'¿Cuántas máquinas se dirigen a tomar Zion?',
'¿Cuántas veces se dice «fuck» en "Pulp Fiction"?',
'¿Cuántas vueltas había que dar al circo en la carrera de carros de "Ben Hur"?',
'¿De qué ciudad eran naturales los protagonistas de "Starship Troopers"?',
'¿De qué color es el sable láser del maestro Yoda"',
'¿De qué estaba hecha la ciudad sumergida del Capitán Nemo?',
'¿De qué marca era el camión que ganó Stallone en "Yo el Halcón"?',
'¿En qué año transcurre "Avatar"?',
'¿En qué cuerpo celeste estaba la mina de "Atmósfera Cero"?',
'¿Qué actor interpreta a "El Rompehuevos" en "Jay y Bob el silencioso contraatacan"?',
'¿Qué actriz protagonizó "Grease 2"?',
'¿Qué arma inventó Duran Duran?',
'¿Qué estrella de rock interpreta a Sally en "Dead Man"?',
'¿Qué famoso deportista aparecía en la versión estrenada en cines de "Gremlins 2"?',
'¿Qué famoso grupo musical aparece en "Regreso al Futuro III"?',
'¿Qué humorista dirige el coro de "Y si no... nos enfadamos"?',
'¿Qué número llevaba Michael J. Fox en el equipo de baloncesto de "Teen Wolf"?',
'¿Qué personaje quería una "plétora de piñatas" para su fiesta de cumpleaños?',
'¿Qué tres lenguas habla William Wallace en "Braveheart"?',
'¿Quién dobla al niño de "Mira Quién Habla" en la versión española?',
'¿Quién es el líder del grupo que toca en la cantina de Star Wars?',
'¿Cómo se llama el habitual doblador español de Bruce Willis?',
'¿Como se llama el protagonista de "Final Fantasy VIII"?',
'¿Cómo se llama el protagonista de "Pokémon"?',
'¿Cómo se llama el tigre de los Frosties de Kellogg´s?',
'¿Cómo se llama la hija de Omaíta?',
'¿Cómo se llamaba el caballo de Jesús Gil?',
'¿Cómo se llamaba el hijo ficticio de Mané?',
'¿Cómo se llamaba el mago que se auto imponía medallas gigantes?',
'¿Cómo se llamaba el personaje gafas gigantes de "Al Ataque!"?',
'¿Cómo se llamaba el prostíbulo de "Farmacia de Guardia"?',
'¿Cómo se llamaba el tigre de Jesulín de Ubrique?',
'¿Cómo se llamaba la chica que le tiró un huevo al Niño del Mechero?',
'¿Cómo se llamaban las chicas de "Ay, qué calor"?',
'¿Cómo se llamaban las dos bailarinas oficiales de Rodolfo Chiquilicuatre?',
'¿Cómo se llaman Faemino y Cansado?',
'¿Cuál de las siguientes criaturas no tiene cuernos?',
'¿Cuál de las siguientes series no es creación de Aaron Spelling?',
'¿Cuál de los siguientes personajes no ha sido actor de doblaje?',
'¿Cuál de los siguientes personajes nunca fue a la Universidad?',
'¿Cuál de los siguientes productos Bertín Osborne no existe?',
'¿Cuál es la nacionalidad de Georgie Dann?',
'¿Cuál es la profesión de los hermanos Mario?',
'¿Cuál es nombre de Chiquito de la Calzada?',
'¿Cuáles son los nombres de Hannah y Barbera respectivamente?',
'¿Cuántos fantasmas persiguen al Comecocos?',
'¿Cuántos superpoderes tiene Batman?',
'¿De qué color era el hipopótamo de Ausonia?',
'¿De qué provincia es Carlos Jesús?',
'¿De qué región es natural Conan?',
'¿De qué tenían forma los Drakis de Matutano originales?',
'¿En qué país opera Sagat?',
'¿En qué periódico trabaja Clark Kent?',
'¿En qué tres zonas se ha de aplicar Vick´s Vaporub?',
'¿Qué actor tiene una marca de pantalones tejanos aptos para practicar artes marciales?',
'¿Qué animal aparece en el escudo de la casa de Huffelpuff?',
'¿Qué arte marcial practica Steven Seagal?',
'¿Qué cineasta abandonó a su mujer para casarse con la hija adoptiva de ambos?',
'¿Qué director de cine dirigió el videoclip de Michael Jackson "Bad"?',
'¿Qué fármaco toma el protagonista de "Metal Gear Solid" para evitar temblores?',
'¿Qué fue antes: la baticao, la cóctelcao o el reloj robot?',
'¿Qué grupo de guerreros maleantes no estaba afiliado ni a He-Man ni a Skeletor?',
'¿Qué grupo de maleantes no estaba afiliado ni a He-Man ni a Skeletor?',
'¿Qué humorista decía "ozú ozé, ozú ozé"?',
'¿Qué número da nombre al golpe especial de Rey Misterio?',
'¿Qué objeto contundente solía llevar Margarita Seisdedos en el bolso?',
'¿Qué personaje de "Street Fighter 2" fue perdido por su madre cuando era pequeño?',
'¿Qué programa infame presentaba Bertín Osborne disfrazado de astronauta?',
'¿Qué significan las siglas DVD?',
'¿Qué significan las siglas VHS para vídeo?',
'¿Quién era el líder de la Horda del Terror?',
'¿Quién es el archienemigo de Action Man?',
'¿A qué precio se vendía el "Lote Venecia" en televisión?',
'¿A quién liberó Han Solo de la esclavitud?',
'¿Cómo se dice anillo en lengua negra?',
'¿Cómo se escribe correctamente el apellido de Dan?',
'¿Cómo se escribe correctamente el apellido de David?',
'¿Cómo se escribe correctamente el apellido de Lando?',
'¿Cómo se llama el general que aparece en los cómics de Superlópez?',
'¿Cómo se llama la marmota del día de la marmota?',
'¿Cómo se llama la novia de Patrick Bateman en "American Psycho"?',
'¿Cómo se llamaba el cocodrilo de Jesús Gil?',
'¿Cómo se llamaba el hipopótamo de Ausonia?',
'¿Cómo se llamaba el playboy espacial del videojuego de Dinamic?',
'¿Cómo se llamaba la "montaña tortuga" de "La Historia Interminable"?',
'¿Cómo se llaman los personajes cuentachistes de Faemino y Cansado?',
'¿Cómo sonaba el teléfono de Krispín Klander que sorteaban en ",,,Cruzamos el Mississippi"?',
'¿Cuál de estas naves no tiene alas móviles?',
'¿Cuál de las siguientes variedades de aceite Bertín Osborne no existe?',
'¿Cuál de los siguientes discos no existe? ',
'¿Cuál de los siguientes personajes no es zurdo?',
'¿Cuál de los siguientes personajes no presentaba "La Quinta Marcha"?',
'¿Cuál de los siguientes personajes nunca grabó un disco?',
'¿Cuál de los siguientes personajes nunca ha ganado un oscar?',
'¿Cuál de los siguientes planetas no existe en el universo Star Wars?',
'¿Cuál es el galo más viejo de la aldea de Astérix?',
'¿Cuál fue el plagio de los Transformers fabricado por Tente?',
'¿Cuántos niveles tiene Minas Tirith?',
'¿De qué color tienen los ojos los Fremen?',
'¿De qué reino fue rey Conan?',
'¿En qué lugar se ubica la última pantalla del "Pang" original?',
'¿En qué mapa de "Black Ops Zombies" no puedes beber Quick Revive?',
'¿En qué país nació J.R.R. Tolkien?',
'¿Qué actor de Holywood fue miembro de los New Kids on the Block?',
'¿Qué actor porno protagoniza "El Poli, el lama y la que los lame"?',
'¿Qué estrella de artes marciales tiene una marca de bebida energética?',
'¿Qué estrella de la canción abandonó temporalmente su carrera para estudiar los ovnis?',
'¿Qué personaje de "Commandos" podía bucear?',
'¿Qué programa presentaba Paula Vázquez cuando se operó la nariz?',
'¿Qué significaban las siglas F.B.I. para Javier Cárdenas?',
'¿Qué tres complementos acompañaban a la figura de acción original de He-Man?',
'¿Qué vehículo servía de transporte al ninja del "Saboteur 2" al principio del juego?',
'¿Quién cantaba "Paca te clavé la estaca"?',
'¿Quién compuso la banda sonora de "La Princesa Prometida"?',
'¿Quién era la voz en off de "El Precio Justo"?',
'¿Quién es último Czarniano?',
'¿Quién interpretaba a Doña Paca?',
'¿Quién interpretó el tema original que inspiró "Hijo de Puta Hay que Decirlo Más"?',
'¿Quién presentaba el primer programa español en el que actuaron Europe?',
'¿A qué futbolista le cantó Leonardo Dantés en su primera aparición televisiva?',
'¿A qué sabían los Doritos Capoeira?',
'¿Cómo se dice "soledad" en Klingon?',
'¿Cómo se escribe correctamente el apellido de Arnold?',
'¿Cómo se llama la bebida energética comercializada por Steven Seagal?',
'¿Cómo se llama la secta liderada por Kirk Cameron?',
'¿Cómo se llamab el difunto esposo de Doña Rogelia"?',
'¿Cómo se llamab el quinto hermano Marx?',
'¿Cómo se llamaba el cantante que acompañaba al Trío Resplandor?',
'¿Cómo se llamaba el dúo cómico de Santiago Urrialde?',
'¿Cómo se llamaba el felino que se convertía en Battle Cat?',
'¿Cómo se llamaba el león de Mari Carmen y sus Muñecos?',
'¿Cómo se llamaba el libro de autoayuda que anunciaba el futbolista Donato?',
'¿Cómo se llamaba la mascota ideológica de Chimo Bayo?',
'¿Cómo se llaman las cuatro muñecas Bratz?',
'¿Cómo se llamó la primera versión instantánea del Cola-Cao?',
'¿Con cuántos cañones cuenta la versión de 2009 del barco pirata de Playmóbil?',
'¿Cuál de estos jugadores de baloncesto no tuvo unas zapatillas con su nombre?',
'¿Cuál de los siguientes dinosaurios nunca existió?',
'¿Cuál de los siguientes dinosaurios nunca existió?',
'¿Cuál de los siguientes discos no existe?',
'¿Cuál de los siguientes ingredientes no está contenido en la Nocilla?',
'¿Cuál de los siguientes personajes nunca grabó un disco?',
'¿Cuál era el premio final del concurso "Si lo sé... no vengo"?',
'¿Cuál es el grito de cabreo de Lobo?',
'¿Cuál es el Príncipe de las galletas?',
'¿Cuántas alas tiene un T-16?',
'¿Cuántos hijos tuvieron Han Solo y la Princesa Leia?',
'¿Cuántos niveles tenía el "Kung-Fu Master"?',
'¿De qué color eran los paquetes de tabaco Trujas?',
'¿De qué localidad es natural La Veneno?',
'¿De qué marca era la bolsa de Rita la Cantaora?',
'¿De qué murió Matusalén?',
'¿En qué año nació Chuck Norris?',
'¿En qué fecha murió Michael Landon?',
'¿En qué órgano se localizó el cáncer que mató al divino Michael Landon?',
'¿En qué programa apareció por primera vez Leonardo Dantés?',
'¿En qué programa musical colaboraba Paco Pil?',
'¿Qué actriz hacía de prostituta en "Un, Dos, Tres..."',
'¿Qué café anunciaba Carmen Maura?',
'¿Qué cantante no interpretó el tema de Gollum de "Las Dos Torres" debido a su embarazo?',
'¿Qué dado se lanza más veces en una partida de AD&D?',
'¿Qué dios aparece en el escenario de Dhalsim en "Street Fighter II"?',
'¿Qué famoso cantante pop actúa en la discoteca de "Karate Kid 3"?',
'¿Qué friki fue electrocutado en "F.B.I." de Javier Cárdenas?',
'¿Qué luchador de la WWF tiene como verdadero nombre Terry Bollea?',
'¿Qué marca de cacao en polvo anunciaba Butragueño?',
'¿Qué marca de televisores anunciaban Pajares y Esteso?',
'¿Qué marca de tónica anunciaba Arturo Fernández?',
'¿Qué milagroso aparato gimnástico de Teletienda anunciaba Suzanne Sommers?',
'¿Qué niño mejicano se hizo internacionalmente famoso por caerse a un río?',
'¿Qué título nobiliario tenía Lando Calrissian?',
'¿Quién canta la canción "Smile" en la banda sonora de "Chaplin"?',
'¿Quién fue el primer presentador/a de "El Gordo"?',
'¿Cómo se llama el alcalde de Quahog?',
'¿Cómo se llama el amado de Guerrero Luna? ',
'¿Cómo se llama el bar de "Padre de Familia"?',
'¿Cómo se llama el bosque donde vive Winnie the Pooh?',
'¿Cómo se llama el científico que creó a las Supernenas?',
'¿Cómo se llama el hermano adoptado de Kyle de South Park?',
'¿Cómo se llama el hermano de Koji Kabuto?',
'¿Cómo se llama el mejor amigo de Dora la Exploradora?',
'¿Cómo se llama el mejor amigo de Yamcha?',
'¿Cómo se llama el mono enemigo de las Súper Nenas?',
'¿Cómo se llama el oso de peluche de Stewie Griffin',
'¿Cómo se llama el profesor gay de "South Park"?',
'¿Cómo se llama la chica de Tidus en "Final Fantasy X"?',
'¿Cómo se llama la hermana de Dexter de "El Laboratorio de Dexter?',
'¿Cómo se llama la novia "fiel" de Isidoro?',
'¿Cómo se llama la novia de Calimero?',
'¿Cómo se llama la primera esposa de Cleveland de "Padre de Familia"?',
'¿Cómo se llamaba el científico de los cómics de Tintín?',
'¿Cómo se llamaba el hermano gemelo "defectuoso" de Bart Simpson?',
'¿Cómo se llamaba el jefe de los Dinosaucers buenos?',
'¿Cómo se llamaba el malo de "Dragones y Mazmorras"?',
'¿Cómo se llamaba la animadora fan de Oliver Aton?',
'¿Cómo se llamaba la chica de la que se enamoró Obelix?',
'¿Cómo se titula el culebrón protagonizado por Calculón?',
'¿Cómo se titulaba la maqueta que grabó Kirk Van Houten?',
'¿Cuál ara el verdadero nombre de Heidi?',
'¿Cuál era la profesión de Ned Flanders antes de abrir el Zurditorium?',
'¿Cuál es el nombre completo de Cartman?',
'¿Cuál es el nombre del Doctor Kabuto?',
'¿Cuál es el nombre del Señor Cangrejo?',
'¿Cuál es el primer deseo que se le pide al dragón de la bolas mágicas en "Bola de Dragón"?',
'¿Cuál es el superhéroe favorito de Shin Chan?',
'¿Cuál es la afición favorita del Reverendo Lovejoy?',
'¿Cuál es la frase más famosa de Fission Boy?',
'¿Cuál es la otra identidad de He-Man?',
'¿Cuál fue el primer deseo que pidió Aladdin al genio en la película de Disney?',
'¿Cuándo cambiaba Lunch de personalidad en "Bola de Dragón?',
'¿Cuántos años estuvo congelado Fry en "Futurama"?',
'¿Cuántos miembros componían los Power Rangers?',
'¿Cuántos pelos tiene Homer Simpson en la cabeza? ',
'¿De qué color le gustaban a Chicho Terremoto las bragas?',
'¿Dónde se cambiaba de ropa Hong Kong Phoey?',
'¿En qué año nació Lisa Simpson?',
'¿En qué ciudad viven las Supernenas?',
'¿En qué planeta se emite con aproximadamente mil años de retraso "Abogada Soltera"?',
'¿Qué actriz dobló en versión original a la jefa de las hienas de "El Rey León"?',
'¿Qué arma usaba la tortuga Leonardo?',
'¿Qué comian los Fraggel Rock?',
'¿Qué grupo musical interpretó el tema principal de "La Vuelta al Mundo en Ochenta Días"?',
'¿Qué instrumento toca Calamardo?',
'¿Qué profesión tenía el padre de Oliver Aton?',
'¿Qué profesión tenía el padre de Tom Baker?',
'¿Qué utiliza Bender como combustible?',
'¿Quién pilota a Afrodita A?',
'¿Quién practicaba el "tiro del gato"?',
'Si la Fuerza Animal de las Fuerza Especiales de Freezer aguanta la respiración...',
'¿A qué especie de dinosaurio pertenece Piecito?',
'¿Cómo se llama el bárbaro de "Dragones y Mazmorras"?',
'¿Cómo se llama el caballero de "Dragones y Mazmorras"?',
'¿Cómo se llama el caballero de oro de Tauro?',
'¿Cómo se llama el guardia al que putea el Oso Yogui?',
'¿Cómo se llama el zorro de "David el Gnomo"?',
'¿Cómo se llama la computadora de Ulises 31?',
'¿Cómo se llama la padawan de Anakin Skywalker?',
'¿Cómo se llamab el saltamontes colega de la abeja Maya?',
'¿Cómo se llamaba el amigo gordito de la Pequeñña Lulú?',
'¿Cómo se llamaba el amigo limón de Naranjito?',
'¿Cómo se llamaba el malo de La Vuelta al Mundo en Ochenta Días al que le brillaba el ojo?',
'¿Cómo se llamaba el pájaro amigo de Heidi?',
'¿Cómo se llamaba el perro de Fry?',
'¿Cómo se llamaba el perro de la sobrina del Inspector Gadget?',
'¿Cómo se llamaba la nave de Comando G?',
'¿Cómo se llamaba la niña de "Los Fruitis"?',
'¿Cómo se llamaba la sobrina del Inspector Gadget?',
'¿Cómo se llaman los dos policías compañeros del Jefe Wiggum?',
'¿Cómo se llaman los dos principales oficiales del ejército clon?',
'¿Con quién vive Johnny Bravo?',
'¿Cuál era la profesión de Ordenalfabétix?',
'¿Cuál era la profesión del padre de Tom Baker?',
'¿Cuál es al ataque favorito de Bobobo?',
'¿Cuál es el juego favorito de Rod y Todd flanders?',
'¿Cuál es el nombre del alferáz en "Sargento Keroro"?',
'¿Cuál es el nombre del doctor Zoidberg?',
'¿Cuál es el nombre real de Tony el Gordo (Fat Tony)?',
'¿Cuál es el signo zodiacal de Peter Griffin?',
'¿Cuáles eran los nombres de los hermanos Derrick en la versión castellana de "Campeones"?',
'¿De qué color es el pañuelo de Lucky Luke?',
'¿De qué color tiene el pelo Kyle en "South Park"?',
'¿De qué están hechas las heces de Mordisquitos?',
'¿De qué nacionalidad eran las películas porno protagonizadas por la madre de Cartman?',
'¿En qué año nació Lisa Simpson?',
'¿En qué convertía Tejo a sus enemigos en "Los Aurones"?',
'¿En qué equipo de la liga española jugó Oliver Aton?',
'¿En qué equipo jugaba Julian Ross?',
'¿En qué idioma habla Supervaca en la versión original de "Vaca y Pollo"?',
'¿En qué universidad se graduó el Señor Burns?',
'¿Qué animal era el padre adoptivo de Alfred J. Kwak?',
'¿Qué caballero de oro profesa el budismo?',
'¿Qué dinosaurio viajó al futuro para hacerse colega de unos horteras californianos?',
'¿Qué forma tiene la casa del Señor Cangrejo?',
'¿Qué piloto de los Autos Locos conducía un avión?',
'¿Quién creó al ratón Rasca?',
'¿Quién dobla al castellano al Inspector Gadget?',
'¿Quién dobló en versión original al gallo de "Chicken Run"?',
'¿Quién era el capitán del Flainet en la versión en castellano de "Campeones"?',
'¿Quién fue el primero en invocar al dragón de las bolas mágicas en "Bola de Dragón"?',
'¿A qué serie de dibujos acompañaban los cortos de Chilly Willy?',
'¿Cómo se escribe correctamente el apellido de Apu?',
'¿Cómo se llama el caballero de oro de Aries?',
'¿Cómo se llama el caballero de oro de Escorpión?',
'¿Cómo se llama el Dinobot volador?',
'¿Cómo se llama el hermano mayor de Freezer?',
'¿Cómo se llama el hermano mayor de Thais en "Ulises XXXI"?',
'¿Cómo se llama el líder de los Thundercats?',
'¿Cómo se llama el malo de "El Inspector Gadget"?',
'¿Cómo se llama la espada de Kurosaki Ichigo?',
'¿Cómo se llama la fuente de energía que utilizan los Wimelef para funcionar?',
'¿Cómo se llama la novia de Cuttlas?',
'¿Cómo se llamaba el cuervo amigo de Pepita Pulgarcita?',
'¿Cómo se llamaba, en castellano, el insecto colega del Maestro Kayto de Bola de Dragón?',
'¿Cómo se llamaba el ordenador parlante de Calculín?',
'¿Cómo se llamaba el primer amor de Candy Candy?',
'¿Cómo se llamaba el robot de la serie de Naranjito?',
'¿Cómo se llamaba la madre de Mafalda?',
'¿Cómo se llamaba la niña que se convertía en Pepita Pulgarcita?',
'¿Cómo se llaman el padre y el niño indios que viven al pie de la torre de Karin?',
'¿Cómo se llaman las dos mujeres-gato pupilas del caballero Folken?',
'¿Con quién se fusionó Piccolo en Namek?',
'¿Contra qué otra organización luchaba M.A.S.K.?',
'¿Cuál de estos personajes no era amigo de Don Gato?',
'¿Cuál de estos personajes no era amigo de Don Gato?',
'¿Cuál era el apellido de Arturito, de "Las Supernenas"?',
'¿Cuál era el apellido de Chicho Terremoto en la versión en castellano?',
'¿Cuál era el nombre del padre de Arturito, de "Las Supernenas"?',
'¿Cuál era el tiro más mortífero de Patrick Everett?',
'¿Cuál es el apellido de Ichigo?',
'¿Cuál es el nombre original de Pedro Picapiedra?',
'¿Cuál es el número del equipo de Naruto, Sasuke y Sakura?',
'¿Cuál es el segundo nombre de Stewe Griffin?',
'¿Cual es el simbolo de "amigo" de "20th Century Boys"?',
'¿Cuál es la frase más famosa de Calimero?',
'¿Cuál no era un superpoder del Sheriff del Espacio?',
'¿Cuál no era uno de los hijos de la Pantera Rosa?',
'¿De qué personaje de "The Rocky Horror Picture Show" se disfrazó el Doctor Heabert?',
'¿De qué sistema era el único amor de Obi Wan Kenobi?',
'¿De quién fue maestro el caballero de oro de Acuario?',
'¿En qué colegio estudiaba Ranma?',
'¿En qué disciplina ganó una medalla de oro olímpica Roger, de "Padre made in U.S.A."?',
'¿En qué serie de dibujos unos niños viajaban en el tiempo gracias a una Biblia Mágica?',
'¿Qué actor pone voz en versión original a Adam West en "Padre de Familia"?',
'¿Qué animal era Chilly Willy?',
'¿Qué animal era Manotas?',
'¿Qué animal era Tristón, el amigo de Leoncio?',
'¿Qué arma usa Pantro en "Thundercats"?',
'¿Qué caballero de bronce no tiene blanco en los ojos?',
'¿Qué documento tenían que encontrar Astérix y Obélix en la casa de los locos?',
'¿Qué equipo ostenta la primera posición en el ránking histórico de "Autos Locos"?',
'¿Qué personaje de "Campeones" era karateka?',
'¿Qué recomendaba Superatón al final de cada capítulo?',
'¿Qué tipo de sombrero lleva Mr. Magoo?',
'¿Quién era el archienemigo de Comando G?',
'¿Quién es también conocido como "El Pistolero Molecular"?',
'¿Quién lleva el dorsal 1 de los Autos Locos?',
'¿Quién lleva el dorsal 7 de los Autos Locos?',
'¿A qué medicamento está enganchado el Doctor House?',
'¿Cómo llaman a los zombies los protagonistas de "The Walking Dead"?',
'¿Cómo murió el amigo de David al principio de "Sensación de Vivir"?',
'¿Cómo murió Trevor en "El Príncipe de Bel-Air"?',
'¿Cómo se llama el barco de Chanquete?',
'¿Cómo se llama el chico del que está enamorado el "Joven Rappel"?',
'¿Cómo se llama el director del colegio de "Salvados por la Campana"?',
'¿Cómo se llama la espada de Jon Nieve?',
'¿Cómo se llama Pepito Grillo en la serie "Érase una Vez"?',
'¿Cómo se llamaba el alguacil calvo de "Juzgado de Guardia"?',
'¿Cómo se llamaba el bar de "Al Salir de Clase"?',
'¿Cómo se llamaba el hijo menor de la familia Banks de Bel-Air?',
'¿Cómo se llamaba el jefe de McGyver?',
'¿Cómo se llamaba el perro que aparecía "Los Fragle"?',
'¿Cómo se llamaba el policía de "Farmacia de Guardia"',
'¿Cómo se llamaba el quinto miembro masculino del Equipo A?',
'¿Cómo se llamaba el súpercomediante que interpretaba al Chavo del Ocho?',
'¿Cómo se llamaba la casa de chicas frescas de "Farmacia de Guardia"?',
'¿Cómo se llamaba la hermana de Waldo Faldo?',
'¿Cómo se llamaba la mejor amiga de Blossom?',
'¿Cómo se llamaba la mejor amiga de D.J. Tuner en "Padres Forzosos"?',
'¿Cómo se llamaba la novia del protagonista de "Yo y el Mundo"?',
'¿Cómo se llamaba la primera colaboradora del Equipo A?',
'¿Cómo se llamaban los principales enemigos de los Fragle?',
'¿Cuál era el apellido de Norm en "Cheers"?',
'¿Cuál era el apellido de Sophia en "Las Chicas de Oro"?',
'¿Cuál era la profesión del padre de "Los Problemas Crecen"?',
'¿Cuál era la profesión del padre de Blossom?',
'¿Cuál es la comida favorita de los melmaquianos?',
'¿Cuáles son los dos apellidos de Marciaaaaaaaal?',
'¿Cuáles son los nombres de la gemelas Olsen?',
'¿Cuáles son los tres modos de conducción iniciales del Coche Fantástico',
'¿Cuántos eran los Bio-Man?',
'¿De dónde era el marajá amigo de Don Pimpón?',
'¿De qué actriz está enamorado el Sr. Floppy?',
'¿De qué ciudad partió el vuelo accidentado de "Perdidos"?',
'¿De qué color era el polvo letal que se usaba para matar a los lagartos de "V"?',
'¿De qué planeta procedía Alf?',
'¿En cuál de estas series aparecía Lorenzo Lamas?',
'¿En qué grupo tocaba Charlie de "Perdidos"?',
'¿En qué serie debutó Leonardo Di Caprio?',
'¿En qué universidad estudió Philip Banks?',
'¿Qué actor interpretaba a Steva Urkel?',
'¿Qué actor protagonizaba "Arnold"?',
'¿Qué animal aparece en el emblema de los Stark?',
'¿Qué animal evolucionado habitaba en la nave de "Enano Rojo"?',
'¿Qué dos personajes aparecen en la foto que cuelga en la habitación de Enjuto Mojamuto?',
'¿Qué instrumento musical toca Steve Urkel?',
'¿Qué instrumento tocaba Charlie en Drive Shaft?',
'¿Qué personaje de "V" era motorista semiprofesional?',
'¿Qué pieza de ajedrez tenía dibujada el camión laboratorio de "El Coche Fantástico"?',
'¿Qué profesión tenía el padre de Pipi Calzaslargas?',
'¿Qué profesor de "Salvados por la Campana" hablaba a toda velocidad?',
'¿Qué usaba Diego en "Los Serrano" para amenazar a sus hijos?',
'¿Quién convertía a sus enemigos en frutas en "Los Aurones"?',
'¿Quién corrió por la playa gritando "Chanquete ha muerto"?',
'¿A qué velocidad podía circular El Halcón Callejero gracias al modo Hiperpropulsión?',
'¿Cámo se llama el casero de Chris Peterson?',
'¿Cómo se llamaba el ayudante del detective Spencer?',
'¿Cómo se llamaba el colectivo de chicas picantes que actuaba en "Ay Qué Calor"?',
'¿Cómo se llamaba el copiloto de "El Trueno Azul"?',
'¿Cómo se llamaba el detective protagonista de "Calor Tropical"?',
'¿Cómo se llamaba el dueño del bar frecuentado por Chanquete?',
'¿Cómo se llamaba el espíritu malvado de "Twin Peaks"?',
'¿Cómo se llamaba el hijo o hija menor de "Los Problemas Crecen"?',
'¿Cómo se llamaba el juez de "Juzgado de Guardia"?',
'¿Cómo se llamaba el perro de Punky Brewster?',
'¿Cómo se llamaba el programa de hipnosis presentado por Bibí Andersen?',
'¿Cómo se llamaba el programa televisivo de "La Trinca"?',
'¿Cómo se llamaba la estrella de la canción a la que le salvaron la vida Javi y Pancho?',
'¿Cómo se llamaba la oveja de peluche de Balki Bartokomus?',
'¿Cómo se llamaba la prima pesada de Steve Urkle?',
'¿Cómo se llamaba la secretaria de Remington Steel?',
'¿Cómo se llamaba la segunda ingeniera de laboratorio de "El Coche Fantástico"?',
'¿Cómo se llamaban las respectivas novias de Balki y Larry?',
'¿Cómo se llamaban los dos compañeros del Gran Héroe Americano?',
'¿Cómo se llaman los amigos de Pipi Calzaslargas?',
'¿Cómo se llaman los cinco protagonistas de "Los Fragle"?',
'¿Cómo se titulaba la canción compuesta por Curtney Love en "Muchachada Nui"',
'¿Con qué mote llamaba su madre a Philip Banks de pequeño?',
'¿Cuál de estas series es un spin-off de  "Primos Lejanos"?',
'¿Cuál de estos personajes no fue presentador/a de "No te rías que es peor"?',
'¿Cuál de estos personajes no fue presentador/a de "No te rías que es peor"?',
'¿Cuál de estos personajes nunca apareció en "Padres Forzosos"?',
'¿Cuál era el apellido de los padrastros de Webster?',
'¿Cuál era el nombre de la Señorita Topisto?',
'¿Cuál era el rango militar de H.M. Murdock?',
'¿Cuál era la especialidad del Doctor Cliff Huxtable?',
'¿Cuál era la profesión de las novias de Balki y Larry?',
'¿Cuál es el actor favorito de Borja en "Qué Vida más Triste"?',
'¿Cuál es el lema de la casa Baratheon?',
'¿Cuál es el nombre de pila del agente Cooper de "Twin Peaks"?',
'¿Cuál es el segundo nombre de Rachel en "Friends"?',
'¿Cuál es el verdadero nombre de Oliver Aton?',
'¿Cuántas puertas hay en el pasadizo del Superagente 86 sin contar la cabina telefónica?',
'¿De qué equipo de baloncesto era Webster?',
'¿De qué marca era el coche de Fénix en "El Equipo A"?',
'¿De qué país era originaria Rose, de "Las Chicas de Oro"?',
'¿De qué pueblo es natural Marlo?',
'¿De quién está enamorada la madre de Kiko en "El Chavo del Ocho"?',
'¿Dónde viven los Lunis?',
'¿En qué localidad vasca transcurre "Qué Vida más Triste"?',
'¿En qué programa salía Pepe Soplillo?',
'¿En qué telecomedia americana apareció Julio Iglesias?',
'¿Qué cantante presentaba "Goles son Amores"?',
'¿Qué coche tenía Julia en "Verano Azul"?',
'¿Qué deporte practicaba A.C. Slater?',
'¿Qué hacían los Fraggle cona las construcciones de los Currys?',
'¿Qué negocio regentaban Matilde y Antonio en "Barrio Sésamo?',
'¿Qué perdió "El Gran Héroe Americano" el día que le regalaron el traje?',
'¿Qué personaje de "Verano Azul" tenía padres divorciados?',
'¿Quién dirigía "El Semáforo"?',
'¿Quién es la Constante en la isla de "Perdidos"?',
'¿Quién llevó a Espinete a Barrio Sésamo?',
'¿Cómo se dice "paz" en el idioma de Los Visitantes de "V"?',
'¿Cómo se llama la compañera de Remington Steele?',
'¿Cómo se llamaba el androide consejero de Valtar en "Galáctica"?',
'¿Cómo se llamaba el barco de Sonny Crockett?',
'¿Cómo se llamaba el hermano de Arnold en "Arnold"?',
'¿Cómo se llamaba el hijo de Sonny Crockett?',
'¿Cómo se llamaba el hijo de Starman?',
'¿Cómo se llamaba el marine secretario de "Papá Comandante"?',
'¿Cómo se llamaba el mono de Pipi Calzaslargas?',
'¿Cómo se llamaba el robot asesor de Yupi y Astraco?',
'¿Cómo se llamaba el ser maléfico de una dimensión paralela en "El Gran Héroe Americano"?',
'¿Cómo se llamaba la amiga, o novia, o hija, o lo que fuera, de Juan Olvido?',
'¿Con qué mote llamaba Ham Tyler a Mike Donovan?',
'¿Cuál de los siguientes actores nunca apareció en "Luz de Luna"?',
'¿Cuál de los siguientes actores nunca apareció en "Luz de Luna"?',
'¿Cuál era la profesión de Joaquín Kremel en "Hostal Royal Manzanares"?',
'¿Cuál es el cantante favorito de Balki Bartokomus?',
'¿Cuál es el cociente intelectual de Sheldon en "Big Bang Theory"?',
'¿Cuál es el nombre del coronel Broyles de "Fringe"?',
'¿Cuál es el nombre original de la rana Gustavo?',
'¿Cuáles era el primer nombre de la esposa de Papá Comandante?',
'¿Cuáles era el segundo nombre de la esposa de Papá Comandante?',
'¿Cuáles eran el nombre y el apellido de la hija de Cristal?',
'¿Cuáles fueron las últimas palabras que dijo Rimmer en vida en "Enano Rojo"?',
'¿Cuántos capítulos tiene "Bonanza"?',
'¿Cuántos intentos tuvo que hacer Kevin Arnold para sacarse el carné de conducir?',
'¿De qué boxeador es amiga Hilary Banks?',
'¿De qué marca era el reloj sumergible que adquirió Chris Peterson por cien dólares?',
'¿De qué se disfrazó Javi en la fiesta de disfraces de "Verano Azul"?',
'¿En qué telecomedia Dolly Parton hacía de secretaria?',
'¿Qué actor interpretaba a Valtar en "Galáctica"?',
'¿Qué animal presentaba "El Bigote de Babel"?',
'¿Qué boxeador no podía parar de reir en la plaza "Tutti Frutti"?',
'¿Qué científico de "Barrio Sésamo" inventaba cosas que ya existen?',
'¿Qué nacionalidad adoptó Indiana Jones en "Las Aventuras del Joven Indiana Jones"?',
'¿Qué ocurría cuando se pulsaba el botón "C" del Coche Fantástico?',
'¿Que película ven Carmela Soprano y el Padre Phil la noche que éste pasa en casa de ella?',
'¿Qué profesión tenía el cuñado del doctor Nacho Martín?',
'¿Qué serie de Vicente Escrivá estaba parcialmente basada en "Cyrano de Bergerac"?',
'¿Qué superpoder obtenía el Gran Héroe Americano cuando dejaba la mente en blanco?',
'¿Qué telecomedia británica transcurría en una hamburguesería?',
'¿Quién absorbió el poder del tiempo de la Tardis al mirar dentro de ella en "Doctor Who"?',
'¿Quién compuso la música de Miami Vice?',
'¿Cómo se llama el protagonista de "Golpe en la Pequeña China", encarnado por Kurt Russel?',
'¿Quién escribió la saga de Harry Potter?',
'¿Cuál de estos personajes aparece en la saga de Harry Potter?',
'¿Qué es un T-1000?',
'¿Quién dirigió "Yo, Robot"?',
'¿Cómo se llama el dragón de 4 estrellas de "Dragon Ball GT"?',
'¿Cómo se llama la espada de John Nieve?',
'¿Cuál es el segundo deseo que se le pide al dragón de las bolas mágicas de la Tierra?',
'¿ Cuál es el símbolo de la casa Tully?',
'¿Quién fue el primero que mató a Son Goku?',
'¿Quién es el creador de Majin Bu?',
'¿Quién es el ganador del 22 torneo de artes marciales de "Dragon Ball"?',
'¿Cómo se escribe el nombre de la más famosa deidad del universo Lovecraft?',
'¿Quién dirigió "Brain Dead"?',
'¿Qué arma acostumbra a llevar Kick ass?',
'¿Cómo se llamaba la tercera parte de "Agárralo como Puedas"?',
'¿Quién fue el primer ganador de "Gran hermano"?',
'"Vivir juntos...',
'"Las lechuzas...',
'¿Qué personaje de "Perdidos" no formaba parte de "Los 6 de Oceanic"?',
'¿De qué personaje de "Perdidos" es la frase "Nos vemos en la otra vida, colega"?',
'¿Cuál de estos objetos es un personaje secundario en "Twin Peaks"?',
'¿Quién es el Sr. Sotomonte?',
'¿Dónde le iba hacer sentir Chuky de Cieza, con lo que tenía en el coche?',
'¿Cuál es el apellido de Ken de "Street Fighter"?',
'¿Quién hacía de Encarna en el sketch de Martes y 13?',
'¿Cámo se llamaba la primera novia de Peter Parker?',
'¿Quién decía "qué mala zuerte, chato"?',
'Meriadoc Brandigamo es de...',
'¿Cuál es el nombre de pila de Plankton?',
'¿Cómo se llama la espada de Lion-o,  protagonista de "Thundercasts"?',
'¿Cuál era el nombre del equipo de baloncesto de Chicho Terremoto?',
'¿Por qué regaña el soldado de guardia a Brian?',
'¿Qué bestia ataca a los Caballeros de la Mesa Cuadrada?',
'¿Cómo se llama el protagonista de "El Jovencito Frankenstein"?',
'¿Cuántas novias tuvo Scott Pilgrim antes de conocer a Ramona Flowers?',
'¿De qué año es la primera película de "El Señor de ños Anillos"?',
'¿De qué se disfrazó Homer Simpson para detener la boda de Apu y Manjula?',
'¿Qué grupo cantaba la canción de "Acción Mutante"?',
'¿Cómo se llama la mejor amiga de Pepa Pig?',
'¿Quién era el panadero de Barrio Sésamo?',
'¿En cuántos capítulos de "El Equipo A" aparece Ana Obregón?',
'¿Cuántas veces muere Krilín?',
'¿Cuál es el arma favorita de Tyresse de "The Walking Dead "?',
'¿Donde tenian su base los Gatos Samurais?',
'¿Cómo dice Sheldon Cooper "zas en toda la boca", en versión original?',
'¿En qué estado se sitúa Smallville, en las películas y la serie de Superman?',
'¿En qué único evento Burney Stinson no lleva traje?',
'¿Cómo murió el Décimo Doctor?',
'¿Cómo se llama el perro de los ladrones de "Los Trotamúsicos"?',
'¿Quien le dio el sombrero de paja a Luffy?',
'¿Qué nombre era la "J" de Alfred J. Kwak?',
'¿Cómo se llama la mascota de Katsura en "Gintama"?',
'¿Cómo se llama el perro de Shin Chan?',
'¿Cuál de los siguientes hilos argumentales de la serie "Gintama" se llevó a la gran pantalla?',
'¿Cuál de estos personajes fue novia de Krilín?',
'¿Cuál es el pesonaje malo de "Doraemon"?',
'¿Cómo se llama al recurso cinematográfico introducido por Hitchcock en sus películas?',
'¿Cuál es la película favorita de Gizmo?',
'¿Contra quiénes tuvo que luchar una vez MacGyver?',
'¿En qué película debutó Sean Astin, Sam en "El Señor de los Anillos"?',
'¿Cuál de estas películas porno no existe?',
'¿Cómo se llamaba la isla donde se encontraba Parqué Jurásico?',
'¿Cuál es la matrícula del coche de Los Cazafantasmas?',
'¿Cómo se llamaba el luchador malísimo de "Kick Boxer"?',
'¿En qué estado se celebra el concurso anual "Pequeña Miss Sunshine"?',
'¿Quién interpretó al Rey Ricardo en "Robin Hood", protagonizada por Kevin Costner?',
'¿Cómo se llamaba el padre de Daniel-Day Lewis en "En el Nombre del Padre"?',
'¿Cómo se llamaba el lobo amigo de Bailando con Lobos?',
'¿En qué planeta tiene su sede la Casa Harkonnen?',
'¿Cuál era el nombre de Sting en la versión española de "Quadrophenia"?',
'¿Cuál de las siguientes películas porno no existe?',
'¿Cuál de estos actores no aparece en "Cabezas Huecas"?',
'¿Qué es lo primero que hay que hacer al subir a un coche en Zombieland?',
'¿Cómo se llama el malo de "Flash Gordon"?',
'¿Qué actor interpreta al capitán del equipo de fútbol en "Grease"?',
'¿Cuántas temporadas tiene "A dos Metros bajo Tierra"?',
'¿Cuál es la bebida favorita de M.A.?',
'¿Cómo se titula la serie de TVE que transcurre en un pueblo de superdotados?',
'¿De qué marca era el coche de Hawk en la serie "Spencer"?',
'¿Cuál era el apellido de Lourdes en "Farmacia de Guardia"?',
'¿Cómo se llamaba el niño protagonista de "Choki"?',
'¿Qué actor protagonizó la serie "Entrenador"?',
'¿Cuál de estos personajes no apareció en "El Príncipe de Bel Air"?',
'¿Cuántas temporadas tiene "Perdidos"?',
'¿Cómo se llamaba el prostíbulo donde trabajaba Laura Palmer?',
'¿En qué gran ciudad transcurre la primera temporada de "Walking Dead"?',
'¿Cómo se llama la secretaria del agente Cooper de "Twin Peaks"?',
'¿Cómo se llamaba la gata que dio origen al gato súperevolucionado de "Enano Rojo"?',
'¿Qué director de cine aparece en el segundo capítulo de "Los Soprano"?',
'¿Quién dijo "Yo he venido a hablar de mi libro"?',
'¿Cuál de estos productos nunca ha existido?',
'¿Cómo se escribe correctamente el apellido de Dolph?',
'¿Cómo se llama la marca de salsas de Paul Newman?',
'¿Cómo se llamaba el refresco de cola de Schweppes?',
'¿Quién fuel el primer manager de Melody?',
'¿Quién es el autor de la banda sonora de "Historias para no Dormir"?',
'¿Cómo se llama el leopardo de los Cheetos?',
'¿Cuál de estos disfraces no pertenece a los Village People?',
'¿Qué gran mamífero es capaz de soportar la cama Restform, según el anuncio?',
'¿Cuál fue el primer animal en identificarse con los Chocos de Kellog´s?',
'¿A qué producto pertenecía el eslogan "...y una mano para ganar"?',
'¿Cuál de estos súperproductos fue el primero cronológicamente?',
'¿Cómo se llamaba el mayordomo real de "El Jueves"?',
'¿Qué intentaba comerse David Hasselhoff en el famoso vídeo que grabó su hija?',
'¿En qué se convertía el padre de Ranma?',
'¿Cómo se llamaba el grillo de David el Gnomo?',
'¿Qué palabra aparece escrita momentáneamente en el cielo en "El Rey Leon"?',
'¿Qué nombre dio Roger de "Padre Made in U.S.A." a la república caribeña que presidió?',
'¿Cómo se llama el caracol mascota de Bob Esponja?',
'¿De qué color tiene el pelo Kyle de "South Park"?',
'¿Cómo se llama el enemigo de Popeye?',
'¿Cuál es la raza de Mordisquitos?',
'¿Cómo se llama la madre de Simba?',
'¿Cómo se llamaba el más alto de los malos de "Érase un vez el hombre"?',
'¿Cómo se llamaba la medio novia de Tetsuo en "Akira"?',
'¿Cómo se llamaba el reloj parlante de "La Bella y la Bestia"?',
'¿Cómo se llamaba el perro que daba lecciones de baloncesto en "Chicho Terremoto"?',
'¿Cuál de estas armas no estaba presente en la armadure de Libra?',
'¿Qué animal acompañaba al protagonista de "Simbad y su Cinturón Mágico"?',
'¿De qué color es el chándal de "la novia" en Kill Bill I?',
'¿De qué color tenía el pelo el duende "Pumuky"?',
'¿Cuál era el nombre con que le llama su madre a Marty Mcfly en el pasado (V.O.)?',
'¿Cómo se llama la novia de Sheldon Cooper en la serie the "Big Bang Theory"?',
'¿Qué actor que interpretó físicamente a Darth Vader en "Una Nueva Esperanza"?',
'¿Cuál es el título de la película en la que Jean Claude Van Damme se interpreta a si mismo?',
'Nombre de la niña que está desaparecida en la 2° temporada de "Walking Dead"',
'¿Cuál es el superhéroe favorito de Sheldon?',
'¿Cómo se llama la hermana pequeña de Bart Simspn?',
'¿Qué personaje jugable muere en "Final Fantasy VII"?',
'¿Quién fue el maestro de Teal'c?',
'¿Qué era la máquina del tiempo de Bill y Ted?',
'¿Cuál era el modelo de los androides de "Blade Runner"?',
'¿Cómo se llamaba el más famoso tiro de Jason y James Derrick?',
'¿Cómo se llamaba el caballero de oro de Capricornio?',
'¿Cómo se llama el mono hechicero de "El Rey León"?',
'¿Cuál es el nombre original de la serie "Los Caballeros del Zodíaco"?',
'¿De qué color es el sable laser del maestro Windu?',
'¿Cómo se llama la serpiente de "El Libro de la Selva"?',
'¿Cuál era el dino-zord del power ranger azul?',
'¿En qué película aparece un pajaro llamado Zazú?',
'¿Cómo se llama el mejor amigo de Bob Esponja?',
'¿Cuál fue el primer superhéroe en salir del armario?',
'¿Cuál era el nombre del maestro de las tortugas ninja cuando era humano?',
'¿Cómo se llama el hijo de Mulder y Scully?',
'¿Cómo se llamaban las tortugas de Rocky Balboa?',
'¿Cómo llamaba a su padre el pequeño de la familia de dinosaurios Sinclair?',
'¿Qué animal era Optimus Prime en la serie "Beast Wars"?',
'¿Qué papel hacia David Bowie en la película "Dentro del laberinto"?',
'¿Cuál era el nombre de David Bowie en "Dentro del Laberinto"?',
'¿Qué gentilicio gritan los soldados en "El Sargento de Hierro"?',
'¿Qué jugador de la NBA era el copiloto de "Aterriza como Puedas"?',
'¿Cuál era el nombre original de Super Mario?',
'¿Cuál era el nombre del equipo de hockey de Bart Simpson?',
'¿En qué película de Clint Eastwood el protagonista se ganaba la vida criando cerdos?',
'¿Cuál de estas mujeres no fue reportera de "El Informal"?',
'¿En qué luchador mejicano inspiró la película de Jack Black "Súper Nacho"?',
'¿Quién interpretaba a Mallory Knox en "Asesinos Natos"?',
'Nombre en clave de Bob Plissken',
'¿Quién es el protagonista de la versión turca de "La Guerra de las Galaxias"?',
'¿Cuál es el nombre real de Carmen de Mairena?',
'¿Cómo se llamaba la compañera de Belphi en la serie de dibujos?',
'¿Qué tótem utiliza Arthur en "Origen"?',
'¿Cómo se llamaba el coronel que dio la orden al Equipo A de atracar el banco de Hanoi?',
'¿Como se llama el corcel de Sir Didimus en "Dentro del Laberinto"?',
'¿Cómo se llama la novia de D´Artacan?',
'¿Qué famoso humorista aparecía en los tazos?',
'¿Cómo se llamaban los trabajadores de Fraggle Rock?',
'¿Cómo se llamaba el abdominal líder revolucionario de "Desafío Total"?',
'De la canción de Ranma: "Estás aquí, ya estoy soñando...',
'¿Qué le diagnosticaron a Joe Banks en "Joe contra el Volcán"?',
'¿Qué bebían los Waponis en "Joe contra el Volcán"?',
'¿Con qué electrodoméstico golpean en la cara a Bill Murray en 'Los fantasmas atacan al jefe'?',
'¿En que animal se convertía el padre de Ranma en contacto con el agua?',
'¿Que decían los enemigos de la serie Sailor Moon al morir?',
'Como se llama la yegua de Link en el juego Zelda, Ocarina of Time?',
'¿Cuál es el nombre de pila del duque de "Sin tetas no hay paraíso"?',
'¿Cómo se llama la nave del Comando G?',
'¿Cómo se llamaba la langosta que Homer tuvo como mascota?',
'¿Con qué sobrenombre era conocido M.A. Barracus en su infancia?',
'¿Cómo se llama la segunda colaboradora femenina del Equipo A?',
'¿Como se llama el Caballero de Bronce de Pegaso en Saint Seiya Omega?',
'¿De qué arte marcial fue Mark Dacascos siete veces campeon del mundo?',
'¿Cómo se llama el amigo azul de Natsu?',
'¿Cuántas veces llama a la puerta Sheldon?',
'¿Cómo se llama la protagonista de "Con la Muerte en los Talones"?',
'¿Cuál fue el primer Pokémon de Ash?',
'¿Cómo se llama el dios Pokémon?',
'¿Cómo se llama el protagonista de la serie "One Piece"?',
'¿De qué dos tipos es Charizard?',
'Apodo de Erza Scarlett en la serie "Fairy Tail"',
'¿Cómo se llamaban los componentes del grupo CRAG?',
'¿Qué papel interpretó Shannen Doherty en "Sensación de Vivir"?',
'¿Cuál era el verdadero nombre de Gandalf?',
'Saruman es interpretado por...',
'¿Cómo se llama el esposo de Galadriel?',
'"Cuando Zarpa el Amor" es una canción de...',
'¿Quién era el protagonista de "Fresh Prince of Bel-Air"?',
'¿Cuáles son los únicos restaurantes que hay en la ciudad de "Demolition Man"?',
'¿Cómo preferiría morir Frank Drebin?',
'¿Cómo se llamaba el mono de Marco?',
'¿A qué droga fue adicto Jean Claude Van Damme?',
'Marujita Díaz es conocida por su célebre movimiento de...',
'¿Quién disparó al Señor Burns?',
'Los nombres de pila de los agentes especiales Mulder y Scully son..',
'¿Cuál es el modelo del Terminator malo en "Terminator 2"?',
'¿Cómo se llama el perro de Rocky Balboa en la primera parte de la saga?',
'¿Como se llama la hermana de Seiya?',
'¿Cuál es el arma final de Yuna en "FFX"?',
'¿Qué dos coches llevaba Vin Diesel en "A Todo Gas"?',
'¿En qué sector trabaja Homer Simpson?',
'¿Cómo se llama el padre de Légolas?',
'¿Cuál es la especialidad del Dr. Wilson?',
'¿Cómo se llama el padre de John Connor?',
'¿Cómo se llama la protagonista de "True Blood"?',
'¿Cómo se llaman los protagonistas del videojuego "Resident Evil"?',
'¿Cómo se apellida Naruto?',
'¿Qué le escribe Charlie a Desmond a través de un ventanuco antes de morir?',
'¿De qué color es el sable láser de Yoda?',
'¿De qué nos hablaba Fernando Arrabal borracho en un programa de TV?',
'¿Cómo se llama el amigo limón de Naranjito?',
'¿Cómo se llama el ratón amigo de D´Artacan?',
'¿Cómo se llama el oso de la casa azul?',
'¿Cómo se llamaba el grupo musical infantil que cantaba la canción principal de D´Artacan?',
'¿Cómo se llamaba la computadora de la nave de "Ulises 31"?',
'¿Cuál es el signo zodiacal de Homer Simpson?',
'¿Cuál es el nombre de pila del Doctor Jones?',
'¿Cuál es el nombre de la nave principal de "Star Trek"?',
'¿En qué parte de "Terminator" escuchamos la frase "sayonara baby"?',
'Quien interpreto al personaje de marvel Punisher en la 1° pelicula',
'¿Quién era el padre del actor que protagonizó la pelicula "El Cuervo"?',
'¿Cuál es el nombre de pila de Masacre de Marvel Comics?',
'¿Como se llama la gárgola anciana de la series "Gárgoles, Héroes Mitológicos"?',
'¿Quién interpreta a Espartaco en la 1° Temporada de Spartacus?',
'Nombre de pila del Capitán América',
'¿Qué famoso personaje dice Yippee-ki-yay Motherfucker?',
'¿Quién es el namekiano que hereda ser el Dios de la Tierra?',
'¿A quién quieren cazar los humanos en "La Princesa Mononoke"?',
'¿Qué es lo que toca Neo para poder entrar en Matrix por primera vez?',
'¿Cómo se llama el comandante Klingon de "Star Trek Next Generation"?',
'¿Cuál fue la primera película de Disney en la que no aparece ningún humano?',
'¿Cuál es la enfermedad de Koothrappali que le impide hablar con mujeres?',
'¿Cómo se llama el actor que interpreta a Sheldon Cooper?',
'¿Cuál es el C.I. de Leonard de Big bang theory?',
'¿Cómo se llama el niño que lee "La historia interminable"?',
'¿Cómo se llama el dragón de "La Historia Interminable"?',
'¿Cómo se llamaba el ciervo embajador de Inglaterra en la India que ayudó a Willy Fog?',
'¿Cuá era ell nombre de pila del Soldado Patoso?',
'¿De qué película es la banda sonora que suena en los partidos de fútbol de Canal +?',
'¿En qué estado se localiza South Park?',
'¿Cuál es el apellido de los protagonistas de "Supernatural"?',
'¿Qué es Légolas?',
'¿Cómo se llama la hija del Señor Cangrejo?',
'¿Cómo se llama el primo de Dora la Exploradora?',
'¿Cuántos años tiene Caillou?',
'¿Que mote adquiere Walter White en "Breaking Bad"?',
'¿Qué Ferrari conducía Tom Selleck en "Magnum"?',
'¿Cómo se llamaban los Doberman del Señor Higgins en "Magnum"?',
'¿Cómo se llamaban los amigos de Magnum?',
'¿Con qué arma decide Butch salvarle la vida a Marcellus Wallace en Pulp Fiction?',
'¿Cómo se llamaba la chica pelirroja de "Dos Fuera de Serie"?',
'¿Quién es el Quinto Elemento?',
'¿Cuál fue la primera película de Alejandro Amenábar ?',
'¿Cuál fue la primera película de Quentin Tarantino?',
'Nombre del cangrejo de "La Sirenita"',
'Nombre del conejo de "Bambi"',
'¿Quién cantó la canción de "La Historia Interminable"?',
'¿Cómo se llamaban los hijos biológicos de Vito Corleone?',
'"Hola, me llamo Íñigo Montoya, tú mataste a mi padre...',
'¿En qué película no actúa Sting?',
'¿Cuál de estos personajes no es un villano "Spiderman"?',
'¿A quién hay que salvar para salvar el mundo en "Héroes"?',
'¿En qué equipo jugaba Julian Ross?',
'¿Cuál fue el primer largometraje de dibujos animados?',
'¿Cómo se llaman los "Little Einsteins"?',
'¿Cuál de estos superhéroes viste de morado?',
'¿Cómo se llama el hermanastro del profesor Xavier?',
'¿Cómo se llama el loro de Jafar?',
'¿Cuál es la identidad civil de Green Arrow?',
'¿Quién es Dinah Drake?',
'¿Cuál es la ciudad de Green Lantern?',
'¿Quién es el más malo en "El Último Dragón"?',
'¿Qué cantante era el ídolo de Carlton Banks?',
'¿Quiénes tenían un Gran Torino?',
'¿Qué actor protagonizó "Atmósfera Cero"?',
'¿a qué compositor le coge manía Álex en "La Naranja Mecánica"?',
'¿Cómo se llama la esposa de Garbanzo en "Chowder"?',
'¿Cuántas son las Bolas de Dragón?',
'¿Qué profesión ejerce Daniel Faraday en la sexta temporada de "Perdidos"?',
'¿De qué color son los ojos de Conan el Bárbaro?',
'¿Cómo se llama el actor que encarnaba a Murdock en la serie de "El Equipo A"?',
'Los dólares en "El Bueno, El Feo y El Malo" estaban en la tumba del soldado desconocido junto a la de...',
'¿Cómo se llaman los seres que Leela encontró en un planeta lejano y comercializó como comida?',
'¿Cómo se llama el capataz de la Tecno-Union?',
'¿Dónde guarda Marge Simpson los recortes de pelo de sus hijos?',
'¿Qué se decía en el anuncio de Donuts cuando se olvidaban?',
'¿De dónde procede el "Slurm"?',
'¿Por qué el mono diabólico atormentaba a Chris Griffin?',
'¿De qué animal es el ojo que cortan en la película de "Un Perro Andaluz"?',
'¿Cómo se llamaba el malo de "Los Pitufos"?',
'¿Qué queria ser el hermano de Olive en "Pequeña Miss Sunshine"?',
'¿Quién le dedicó un temazo al "miembro viril"?',
'¿Cuál es el mote de Tom Cruise en "Top Gun"?',
'¿Qué serie es la más longeva de la historia de la televisión española?',
'¿Cómo se llama la espada de Frodo?',
'¿En qué planeta nació Superman?',
'¿Cómo se llamaba la hermana de Toni Montana ?',
'¿Quiénes escribieron "Los Cazafantasmas"?',
'¿Qué modelo de coche conducían Thelma y Louise?',
'¿Qué animal se llamaba Misery en la película "Misery"?',
'¿Cómo le llamaba el policía de "Farmacia de Guardia"?',
'¿Cómo se llama la espada de Eddar Stark?',
'¿Cual es el lema de la casa Baratheon? ',
'¿De qué es concejal Enrique Pastor?',
'¿Quién es el inseparable amigo de Hiro Nakamura en "Héroes"?',
'Nombre de los habitantes de las plantas de Epi y Blas',
'¿Quién es el Caballero de las Flores? ',
'¿En qué personaje está inspirado el Doctor House?',
'¿Qué tenía que beber Arale para sobrevivir?',
'¿Cuál es el aminoácido favorito de Sheldon Cooper?',
'¿Cuántas tetas tenía la madre del Penumbra?',
'¿Quién no es miembro fundador de la Patrulla X?',
'¿De qué material era Bender cuando renegó de la tecnología?',
'¿En cuál de estas fechas se  celebra "el día de la aproximación de Pi"?',
'¿Cómo se llama la protagonista de "Sailor Moon" en España?',
'¿De qué país era Marco?',
'¿Cómo se llama la tienda de cómics de "Los Simpsons"?',
'¿Cuál es el segundo nombre de Homer Simpson?',
'¿Cómo se llama el malo de "Doraemon"?',
'¿Cuál es la técnica oculta de los Uchiha?',
'¿Quién mató a Goku por primera vez?',
'¿Cómo se llama el mayordomo de la Princesa Chicle?',
'¿Cómo se llama la princesa más pija de "Hora de Aventuras"?',
'¿Cuál es el instrumento que toca Marceline la Vampira?',
'¿De qué color tiene el pelo Finn el Humano?',
'¿Dónde vive el padre de Marceline de "Hora de Aventuras"?',
'¿Qué publicitaban Los Picapiedra en sus comienzos?',
'¿Qué les pasa a los habitantes de Chuchelandia cuando se asustan?',
'¿Cuáles fueron los primeros caballeros que vistieron armadura en "Saint Seiya"?',
'¿A qué huele el aliento de Jake el Perro?',
'¿De quién era maestro el Caballero de Oro Acuario en el anime de "Saint Seiya"?',
'¿Cómo se llama el padre de la familia Winslow?',
'¿Cual es el nombre de Dientes de Sable en "X-Men"?',
'¿Cómo se llaman las hermanas de Marge Simpson?',
'¿Cómo se llama el personaje que interpreta Bruce Willis en "Pulp Fiction"?',
'¿Qué difunto semidiós compuso la banda sonora de "Conan el Bárbaro"?',
'¿A qué órgano afectó el cáncer que mató a Michael Landon?',
'¿Con qué orden se ordenó a los clones eliminar a todos los Jedis?',
'¿Qué oficial del ejército separatista se asemeja a una araña?',
'¿Cómo se llama el grupo revolucionario del sistema Mandalore?',
'¿Qué caza rebelde de la batalla de Endor tiene mayor potencia de fuego?',
'¿Cuál de estos actores no aparece en "Star Wars Holiday Special"?',
'¿Quién dirigió "Pesadilla antes de Navidad"?',
'¿Quién da voz a Jack en las canciones de "Pesadilla antes de Navidad"?',
'¿Cómo se llamaba el extraterrestre amigo de Chris Peterson en "Búscate la Vida"?',
'¿Cómo se llama el grito más famoso de la historia del cine?',
'¿Quién compuso la banda sonora de "El Pelotón Chiflado?',

    
];
