module.exports = [
    '¿Cual es la frase que pronunció Iñigo Montoya antes de matar al asesino de su padre?',
    '¿Quien interpretaba a la medium de Ghost?',
    '¿Qué vendía el contacto ciego de Top Secret?',
    '¿Con quién estaba condenada a casarse la Princesa Vespa?',
    '¿Como se llamaba el malo de La loca historia de las galaxias?',
    '¿Qué velocidad debe alcanzar el Delorean de “Regreso al Futuro” para viajar en el tiempo?',
    '¿Quien fué el primero robot en conseguir la nacionalidad norteamericana?',
    '¿Que usaban en Demolition Man para limpiarse el "pompis"?',
    '¿Quien interpretó a Conan de pequeño?',
    '¿Cómo se llama la esposa de Pijus Magnificus?',
    '¿Cómo se llama el padre de Chewaka?',
    '¿A que animal tenía miedo Indiana Jones?',
    '¿Cómo se designa al pequeño y ligero caza utilizado por el Imperio Galáctico?',
    '¿De que planeta es originario Darth Vader?',
    '¿Cuál es el nombre de pila del padre de Luke Skywalker?',
    '¿Qué actriz de Friends aparecía en Masters del Universo?',
    '¿Como se llama el personaje de Kurt Russell en 1997: Escape en Nueva york?',
    '¿Actor interpretaba de El Príncipe de Zamunda?',
    '¿Como se llama la mujer de la que se enamora Doc en Regreso al futuro III?',
    '¿Cuantas películas se han hecho de Expediente X?',
    '¿De que universidad vasca era catedrático de teología el padre Berriartua?',
    'En Mallrats, ¿que dibujo se supone que aparece en el cuadro magico del centro comercial si lo miras durante unos segundos?',
    '¿Cual es el color de Quentin Tarantino en Reservoir Dogs?',
    '¿Cual es el autentico nombre de El Vengador toxico?',
    '¿Cómo se puede saber si alguien es una bruja?',
    '¿Cual es el personaje de Bruce Willis en La jungla de cristal?',
    '¿Cómo se llama el compañero de John McLane en "La jungla de Cristal III:La venganza"?',
    '¿Como se llamaba el fantasma verde de Los Cazafantasmas?'
];