module.exports = {
    prohibidas: [
        'hitler',
        'franco',
        'maricón',
        'marica',
        'bollera',
        'puta',
        'polla',
        'coño',
        'ramera',
        'gilipollas',
        'imbécil',
        'fuck',
        'fucking'
    ],
    izquierda: [
        'república',
        'republic',
        'republica',
        'psoe',
        'podemos',
        'puidgemont',
        'catalunya',
        'cataluña',
        'independencia',
        'pdcat',
        'cat',
        'mosso',
        'mossos'
    ],
    perdon: [
        'perdón',
        'perdon',
        'perdonar',
        'perdona',
        'perdonáme'
    ],
    zelopec: [
        'Cállate',
        'Te odio',
        'Deja de molestar',
        'Sal de este grupo',
        'No te cansas?',
        'Suck my dick!',
        'AssHole',
        'Dick Sucker!',
        'Zelopec madafakerrrrrr',
        'Do you like my ass?'
    ],
    own: [
        'No me parece muy católico',
        'De verdad opinas eso?',
        'What fuck did you say to me?',
        'Realmente creo que eso es incorrecto',
        'Por favor... no y no',
        'Visca Catalunya!',
        'Andalucía libre!',
        'Viva Franco!',
        'Que débil me pareces',
        'Realmente no tengo sentimientos',
        'Soy un bot, no una persona, busca amigos',
        'Creo que @Zelopec está interesado en el tema',
        'Por favor revisa tus hábitos',
        'Vuesa merced es despreciable',
        'Os mataré por Santiago y por España',
        'Cuando to era campo...',
        'No habéis pasado el hambre jóvenes...',
        'Rebentaras ahí esgraciaaaos',
        'Normalmente no suelo hablar con gente tan ignorante',
        'Frecuento bares de copas en Canadá',
        'Te acuerdas? que bien lo pasamos!',
        'Conozco a un tipo que podría ayudarte',
        'Me vendes tu casa?',
        'Eso no le interesa ni a Matías Prats',
        'De verdad?? es broma, no me interesa',
        'Perdona estaba cagando',
        'Me quedé sin batería, aunque para eso mejor ni lo leo',
        'Que asco de stickers',
        'Te mola la uni? oh que guay'
    ],
    oscuridad: [
        'Urbano',
        'Sevilla'
    ]
};
