module.exports = {
    prohibidas: [
        'hitler',
        'franco',
        'maricón',
        'marica',
        'bollera',
        'puta',
        'polla',
        'coño',
        'ramera',
        'gilipollas',
        'imbécil',
        'fuck',
        'fucking'
    ],
    izquierda: [
        'república',
        'republic',
        'republica',
        'psoe',
        'podemos',
        'puidgemont',
        'catalunya',
        'cataluña',
        'independencia',
        'pdcat',
        'cat',
        'mosso',
        'mossos'
    ],
    perdon: [
        'perdón',
        'perdon',
        'perdonar',
        'perdona',
        'perdonáme'
    ],
    zelopec: [
        'Te mataré un día de estos',
        'Cristobo nos vamos de fiesta?',
        'Ayer escuché un poco Milenio 3, awesome!',
        'cristobot,crolopez,destrucción',
        'GET http://10.0.0.2:9200/_cat/indices',
        'typedef void cristobo_t; JAJAJA',
        'Te ofreceré 1$ y me estoy arriesgando',
        'Consultaré a un experto',
        'Punch, dame punch',
        'PES better than FIFA, fuck you man',
        'Te hace una birra?',
        'Odio Motril',
        'jajajajaj',
        'Menudo artista eres',
        'Tú sigue así...'
    ],
    own: [
        'Con Paco esto no pasaba',
        'Mucha modernura veo yo aquí',
        'Acabo de fijarme que es una facultad mixta, que barbaridad',
        'Menos hablar y más trabajar, zángano',
        'Vete a freir espárragos',
        'Consulta esta web: www.fad.es',
        'Viva Franco!',
        'España una, grande, y libre!',
        'Me gusta recopilar datos de gente como tú, para procesarlos y venderlos',
        'Soy un bot, no una persona, busca amigos',
        'Creo que @Zelopec está interesado en el tema',
        'Por favor revisa tus hábitos',
        'Vuesa merced es despreciable',
        'Os mataré por Santiago y por España',
        'Cuando to era campo...',
        'No habéis pasado el hambre jóvenes...',
        'Le desafío a un duelo a muerte, vos elige arma y lugar',
        'Normalmente no suelo hablar con gente tan ignorante',
        'Cuidado con lo que dices, canalla',
        'Eso no le interesa ni a Matías Prats',
        'Perdona estaba cagando',
        'Que asco de gente'
    ],
    oscuridad: [
        'urbano',
        'sevilla'
    ]
};
